### ISSUE TITLE
Dictionary phrases sometimes appear to be dropped

### ISSUE THREAD

**Issue by superharry** [universal-automata/liblevenshtein-java#6]
Thanks again for the library!

I think I might have found an issue: it appears that some dictionary entries will be dropped by the transducer when (i) the dictionary is sufficiently large and (ii) there is a longer entry that includes the dropped entry.

Demo code below. The transducer will forget that "Resource" is one of the dictionary entries. Note that the issue will not occur if "Resource" and "Resources" are the only two entries in the mockDictionary.

```java
    List<String> mockDictionary = new ArrayList<String>();
		
		mockDictionary.add("Representatives");
		mockDictionary.add("Resource");
		mockDictionary.add("Resources");
		
		final ITransducer<Candidate> transducer = new TransducerBuilder()
				.algorithm(Algorithm.TRANSPOSITION)
				.defaultMaxDistance(2)
				.dictionary(mockDictionary)
				.build();
		
		for(String query : mockDictionary) {
			
			boolean exactMatchFound = false;
			
			for(Candidate candidate : transducer.transduce(query)) {
				if(candidate.distance() == 0) {
					exactMatchFound = true;
					break;
				}
			}
			
			// There should be an exact match for each query.
			if(!exactMatchFound) {
				System.out.println(query);
				for(Candidate candidate : transducer.transduce(query)) {
					System.out.println("\t" + candidate.term());
				}
			}
			
		}
```

**Comment by dylon** [comment]
Hi @superharry,

I'll take a look at this as I get the time (I've actually been heavily refactoring the code, so this use case helps greatly).  In the meantime, @catap has created a temporary patch that may work for you if your dictionary isn't too large.

Regards,
Dylon

**Comment by dylon** [comment]
This bug was due to an overly-aggressive attempt to reduce memory usage by replacing `DawgNode.isFinal` with a set of final nodes.  The goal was to mark final nodes sparsely, as there are relatively-few of them.  I'll revisit this in the future, but for now have reverted to `DawgNode.isFinal`.

References take up memory too.  Removing unnecessary references can make a huge difference with very large dictionaries.  Consider this: on 64-bit machines, each reference consumes 64-bits of memory for addressing, along with whatever it points to and any metadata the JVM and OS need.  In recent versions of Java, you can enable pointer compression to reduce the bitwidth of pointers to 32-bits, but when you have billions of pointers, their memory can add up quickly.

Feel free to re-open this bug if the issue remains.

**Comment by matanster** [comment]
:+1:
